# Generated by Django 4.2.9 on 2024-03-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_feeder_num_assay_cable_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='pdf_file_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
