from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(UserTable)
admin.site.register(Assay)
admin.site.register(Permit)
admin.site.register(TeamModel)
admin.site.register(PreworkMeeting)
admin.site.register(RiskAssessment)
admin.site.register(SafeWorkProcedure)
admin.site.register(Paramedic)
admin.site.register(Fighter)
admin.site.register(AssignedTask)
admin.site.register(ArtificialSecurityCard)
admin.site.register(RecipientCard)
admin.site.register(ResidenceCard)
admin.site.register(TUVForEquipmentAndDriver)
admin.site.register(FireExtinguisher)
admin.site.register(FirstAid)
admin.site.register(WorkTeam)
admin.site.register(PicturesOfSite)
admin.site.register(SubscriptionNumber)
admin.site.register(CutterCapacity)
admin.site.register(MeterCapacity)
admin.site.register(DepthOfExcavation)
admin.site.register(FossilView)
admin.site.register(CableLength)
admin.site.register(SafetyBarrier)
admin.site.register(Object)
admin.site.register(Obstacle)
admin.site.register(Violation)