# Generated by Django 4.2.9 on 2024-03-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='day',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='month',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='year',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
